### ISSUE TITLE
login improvements

### ISSUE THREAD

**Issue by spreeker** [petities/petitions.eu#19]
- ~~go to your own petitions page when you login.~~
- ~~confirm you email / signature before you login.~~
- ~~my petitions in list, rather than grid: draft, signable, answered and revoked~~
- ~~a link to 'my profile' page~~

**Comment by rrustema** [comment]
line 45 in app/views/shared/_header.html.slim is already internationalised for 'my profile'

**Comment by spreeker** [comment]
There is no single location for a profile. The petition is currently used for that. SO a user might have mutiple locations of profile information. 
On each petition there is information making this a rather "nasty" issue. to be completed after the migration.

**Comment by rrustema** [comment]
upon starting a petition the profile info is copied from the profile of the user who starts the petition. The user can then edit endlessly their petition profile info (details). Stored in the petition table in the database, not the user table. Petitioner can even go into anonimity! Or pretend to be a collective. Multiple profiles possible, for each petition a different one. Possible because we know the user.
