### ISSUE TITLE
confirm address of manually added new user

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#446]
The address of a petitioner manually added by the admin should get confirmed. The instruction used to be until now to set a new password by requesting a reset link from /users/password/new

The request link arrives, setting the new password works, but access is denied. The account needs to be confirmed. 

This procedure was suggested a few dozen times to new users, without complaints so far. User with ticket  ASU-28795-538 is the first one to complain since this codebase is used. It might never have worked. It might have been deleted during a code clean up.

**Comment by skoolstra** [comment]
You are correct, this behaviour was changed in the authentication library. Account confirmation during a password reset was removed because it introduced a security risk. You can read more about that on https://github.com/plataformatec/devise/issues/4006.

The instruction could be changed. When the admin creates a new account, the user automatically receives a email with the confirmation link. Clicking that link confirms the account. A button to resend to confirmation message was added to ActiveAdmin.
